version: '3'

volumes:
  {}

networks:
  sample-project:
      driver: bridge

services:
  app:
    container_name: app
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - PYTHON_VERSION=3.10
    volumes:
      - ./src:/app/src
#    env_file:
#      - .config/.env
    ports:
      - "8000:8000"
    command: start.sh run
    depends_on:
      - worker

  worker:
    build:
      context: ./
      dockerfile: Dockerfile
    command: celery.py -A src worker --loglevel=info --beat
    depends_on:
      - redis
    links:
      - redis

  redis:
    container_name: redis
    image: redis:latest
    ports:
      - "6381:6379"
