# Generated by Django 5.0.7 on 2024-07-14 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_rating_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='username',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='rating',
            old_name='username',
            new_name='author',
        ),
    ]
